# Test TSFresh

In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
#From FFNN_v2

#Load and preprocess the data
folder_path = '500_files'
data = {}

for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    if os.path.isfile(file_path):
        with open(file_path, 'r') as file:
            df1 = pd.read_csv(file_path, header=None, names=['des_flux', 'detrap_en', 'def_conc'], index_col=None, squeeze = True)
            data[filename] = df1
            
# Combine all the data into a single dataframe
df = pd.concat(data.values())

# Drop NaN values
#df = df.dropna()

display(df)

C:\Users\mvigi\AppData\Local\Temp\ipykernel_26144\2509097887.py:11: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  df1 = pd.read_csv(file_path, header=None, names=['des_flux', 'detrap_en', 'def_conc'], index_col=None, squeeze = True)
C:\Users\mvigi\AppData\Local\Temp\ipykernel_26144\2509097887.py:11: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  df1 = pd.read_csv(file_path, header=None, names=['des_flux', 'detrap_en', 'def_conc'], index_col=None, squeeze = True)
C:\Users\mvigi\AppData\Local\Temp\ipykernel_26144\2509097887.py:11: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  df1 = pd.read_csv(file_path, header=None, names=['des_flux', 'detrap_en', 'def_conc'], index_col=None,

des_flux  detrap_en  def_conc
0    1.269745e-10   1.051587  0.011064
1    8.488521e+14   1.185898  0.006066
2    1.239766e+15   1.203310  0.020460
3    1.784721e+15   1.242848  0.005844
4    2.528399e+15        NaN       NaN
..            ...        ...       ...
296  7.160074e+07        NaN       NaN
297 -6.944291e+08        NaN       NaN
298 -5.921441e+08        NaN       NaN
299 -1.240336e+09        NaN       NaN
300  1.267471e+10        NaN       NaN

[150500 rows x 3 columns]

In [6]:
#Instead of shaping by 500, have to shape
#to create a design matrix in TSFresh

#Maybe turn this into a loop?
des_flux=df['des_flux']
des_flux=des_flux.tolist()
num_files=int(len(des_flux)/301)
des_flux=np.reshape(des_flux, [301, num_files])
#des_flux=pd.DataFrame(des_flux)
display(des_flux)
#print(type(des_flux[0]), des_flux.shape)

detrap_en=df['detrap_en']
detrap_en=detrap_en.dropna()
detrap_en=detrap_en.tolist()
num_files=int(len(detrap_en)/4)
detrap_en=np.reshape(detrap_en, [num_files, 4])
detrap_en=pd.DataFrame(detrap_en)
display(detrap_en)
#print(detrap_en, detrap_en.shape)

def_conc=df['def_conc']
def_conc=def_conc.dropna()
def_conc=def_conc.tolist()
num_files=int(len(def_conc)/4)
def_conc=np.reshape(def_conc, [num_files, 4])
def_conc=pd.DataFrame(def_conc)
display(def_conc)
#print(def_conc, def_conc.shape)

array([[ 1.26974494e-10,  8.48852054e+14,  1.23976624e+15, ...,
         1.09468525e+18,  1.05410110e+18,  1.01374691e+18],
       [ 9.73533572e+17,  9.33372391e+17,  8.93179927e+17, ...,
         1.45283577e+17,  1.56600802e+17,  1.68585253e+17],
       [ 1.81254314e+17,  1.94623503e+17,  2.08705093e+17, ...,
        -1.21875351e+10,  5.55010846e+09,  3.62632437e+10],
       ...,
       [ 3.38901374e+11,  5.24502452e+11,  8.20208516e+11, ...,
         3.07298074e+12,  1.82555696e+12, -6.96374298e+10],
       [-1.02285003e+12, -6.88484344e+11,  2.74293460e+10, ...,
         1.83701050e+18,  1.81548044e+18,  1.80407856e+18],
       [ 1.80102564e+18,  1.80484192e+18,  1.81429865e+18, ...,
        -5.92144090e+08, -1.24033587e+09,  1.26747148e+10]])

0         1         2         3
0    1.051587  1.185898  1.203310  1.242848
1    1.255962  1.542662  1.639949  1.861172
2    1.258223  1.457589  1.517217  1.662228
3    1.570379  1.679522  1.763853  1.959120
4    1.004923  1.178099  1.545668  1.996392
..        ...       ...       ...       ...
495  1.294485  1.453706  1.690374  1.989040
496  1.158508  1.184119  1.313477  1.351123
497  1.014578  1.537740  1.540312  1.783217
498  1.031444  1.356689  1.726457  1.997682
499  1.000740  1.275135  1.357167  1.387396

[500 rows x 4 columns]

0         1         2         3
0    0.011064  0.006066  0.020460  0.005844
1    0.011071  0.002566  0.006255  0.002365
2    0.019062  0.015085  0.007964  0.010209
3    0.004553  0.006861  0.009116  0.023333
4    0.024391  0.023542  0.019127  0.006894
..        ...       ...       ...       ...
495  0.006651  0.019913  0.002930  0.007843
496  0.004188  0.013674  0.004737  0.023844
497  0.022527  0.022893  0.003630  0.021321
498  0.014667  0.007541  0.014966  0.018687
499  0.005143  0.001468  0.006096  0.006893

[500 rows x 4 columns]

In [7]:
#TSFresh is not reading in large values
#Like the raw TDS data. Normalize beforehand then
#do TSFresh

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(with_mean=True, with_std=True)
des_flux_norm = scaler.fit_transform(des_flux.reshape(-1, 1))

In [13]:
#make back into a 1d dataframe.

des_flux_norm=pd.DataFrame(des_flux_norm)
display(des_flux_norm)

0
0      -0.844865
1      -0.844526
2      -0.844370
3      -0.844152
4      -0.843855
...          ...
150495 -0.844865
150496 -0.844865
150497 -0.844865
150498 -0.844865
150499 -0.844865

[150500 rows x 1 columns]

In [20]:
#Create an array counting 0 to 499,
#301 times for each count
#This marks the sequential data
#with an id used in TSFresh

des_flux_id = np.arange(0,150500)
des_flux_id = des_flux_id // 301

In [22]:
#Applies the id to the data

display(des_flux_id)
des_flux_norm["id"] = des_flux_id
display(des_flux_norm)

array([  0,   0,   0, ..., 499, 499, 499], dtype=int32)

0   id
0      -0.844865    0
1      -0.844526    0
2      -0.844370    0
3      -0.844152    0
4      -0.843855    0
...          ...  ...
150495 -0.844865  499
150496 -0.844865  499
150497 -0.844865  499
150498 -0.844865  499
150499 -0.844865  499

[150500 rows x 2 columns]

In [24]:
#Checking for proper shape
#and statistics

print(des_flux_norm.shape)
display(des_flux_norm.mean(), des_flux_norm.std(), des_flux_norm.min(), des_flux_norm.max())

(150500, 2)


0    -4.796754e-17
id    2.495000e+02
dtype: float64

0       1.000003
id    144.337758
dtype: float64

0    -0.845754
id    0.000000
dtype: float64

0       5.38192
id    499.00000
dtype: float64

In [31]:
#Concatenates the def_param matrices
#May have to split these and take the mean
#for select_features to accept as a Series
#Can maybe compare two relevance tables to
#extract best features?

def_param = pd.concat([detrap_en, def_conc], axis=1)
def_param["id"] = def_param.index
display(def_param)

0         1         2         3         0         1         2  \
0    1.051587  1.185898  1.203310  1.242848  0.011064  0.006066  0.020460   
1    1.255962  1.542662  1.639949  1.861172  0.011071  0.002566  0.006255   
2    1.258223  1.457589  1.517217  1.662228  0.019062  0.015085  0.007964   
3    1.570379  1.679522  1.763853  1.959120  0.004553  0.006861  0.009116   
4    1.004923  1.178099  1.545668  1.996392  0.024391  0.023542  0.019127   
..        ...       ...       ...       ...       ...       ...       ...   
495  1.294485  1.453706  1.690374  1.989040  0.006651  0.019913  0.002930   
496  1.158508  1.184119  1.313477  1.351123  0.004188  0.013674  0.004737   
497  1.014578  1.537740  1.540312  1.783217  0.022527  0.022893  0.003630   
498  1.031444  1.356689  1.726457  1.997682  0.014667  0.007541  0.014966   
499  1.000740  1.275135  1.357167  1.387396  0.005143  0.001468  0.006096   

            3   id  
0    0.005844    0  
1    0.002365    1  
2    0.010209    2  
3    0.023333    3  
4    0.006894    4  
..        ...  ...  
495  0.007843  495  
496  0.023844  496  
497  0.021321  497  
498  0.018687  498  
499  0.006893  499  

[500 rows x 9 columns]

In [26]:
from tsfresh import extract_features
features = extract_features(des_flux_norm, column_id="id", column_sort="id")

Feature Extraction: 100%|██████████| 20/20 [00:34<00:00,  1.74s/it]


In [41]:
#Display extracted features.
#Filtered features won't run with NaN values, 
#so drop 0__query_similarity_count__query_None__threshold_0.0 column

display(features)
list(features.columns)
#display(features.isna().sum().sum())
features=features.drop(["0__query_similarity_count__query_None__threshold_0.0"], axis=1)

0__variance_larger_than_standard_deviation  0__has_duplicate_max  \
0                                           1.0                   0.0   
1                                           0.0                   0.0   
2                                           1.0                   0.0   
3                                           0.0                   0.0   
4                                           1.0                   0.0   
..                                          ...                   ...   
495                                         0.0                   0.0   
496                                         1.0                   0.0   
497                                         1.0                   0.0   
498                                         0.0                   0.0   
499                                         0.0                   0.0   

     0__has_duplicate_min  0__has_duplicate  0__sum_values  0__abs_energy  \
0                     0.0               0.0     -39.541069     437.925127   
1                     0.0               0.0    -144.239222     117.925582   
2                     0.0               0.0       4.430345     334.461458   
3                     0.0               0.0     -37.360196     204.829269   
4                     0.0               0.0     111.379218     464.279553   
..                    ...               ...            ...            ...   
495                   0.0               0.0     -69.662900     150.997957   
496                   0.0               0.0     -24.651741     425.282503   
497                   0.0               0.0      93.690025     340.354886   
498                   0.0               0.0      21.944503     105.607382   
499                   0.0               0.0    -157.387660     138.787646   

     0__mean_abs_change  0__mean_change  0__mean_second_derivative_central  \
0              0.116149   -2.663928e-08                          -0.005352   
1              0.053782   -8.426667e-11                          -0.002019   
2              0.132604   -9.253877e-11                          -0.002890   
3              0.087392    5.104270e-10                          -0.003541   
4              0.167121    3.788365e-11                          -0.007014   
..                  ...             ...                                ...   
495            0.095009    1.004463e-11                          -0.002072   
496            0.110720    1.697348e-10                          -0.003670   
497            0.173569    4.159036e-10                          -0.005509   
498            0.107445    1.561224e-08                          -0.004284   
499            0.047389    1.687683e-11                          -0.000973   

     0__median  ...  0__fourier_entropy__bins_5  0__fourier_entropy__bins_10  \
0    -0.844526  ...                    0.209069                     0.235155   
1    -0.679535  ...                    0.136002                     0.181214   
2    -0.686175  ...                    0.170467                     0.170467   
3    -0.566277  ...                    0.215617                     0.305728   
4    -0.137914  ...                    0.204871                     0.305728   
..         ...  ...                         ...                          ...   
495  -0.359573  ...                    0.125256                     0.204871   
496  -0.838943  ...                    0.079983                     0.125256   
497   0.081381  ...                    0.228465                     0.290926   
498   0.025826  ...                    0.249958                     0.339942   
499  -0.825912  ...                    0.204871                     0.305728   

     0__fourier_entropy__bins_100  0__permutation_entropy__dimension_3__tau_1  \
0                        0.816524                                    1.438705   
1                        0.821707                                    1.307893   
2                        1.176301                             

500

In [58]:
#Attempting to convert df to
#Series. Its multidimensional,
#may have to take the mean. 

type(def_conc)
def_conc = df.squeeze(def_conc)
type(def_conc)

TypeError: unhashable type: 'DataFrame'

In [57]:


def_param = pd.DataFrame(def_param).to_numpy()
display(def_param)

array([[1.05158736e+00, 1.18589840e+00, 1.20331037e+00, ...,
        2.04598207e-02, 5.84418432e-03, 0.00000000e+00],
       [1.25596152e+00, 1.54266160e+00, 1.63994921e+00, ...,
        6.25458783e-03, 2.36497947e-03, 1.00000000e+00],
       [1.25822251e+00, 1.45758869e+00, 1.51721682e+00, ...,
        7.96364390e-03, 1.02088885e-02, 2.00000000e+00],
       ...,
       [1.01457836e+00, 1.53773973e+00, 1.54031238e+00, ...,
        3.63031450e-03, 2.13208519e-02, 4.97000000e+02],
       [1.03144402e+00, 1.35668867e+00, 1.72645702e+00, ...,
        1.49660559e-02, 1.86868238e-02, 4.98000000e+02],
       [1.00074039e+00, 1.27513497e+00, 1.35716673e+00, ...,
        6.09607345e-03, 6.89274153e-03, 4.99000000e+02]])

In [56]:
#Where I'm currently stuck
#Calculating filtered features from the calculated
#extracted features. Only wants the output target as
#a Series. Choices: Convert def_conc and detrap_en
#into a Series by taking the mean of each row, 
#finding a workaround to allow for the target to 
#be a DataFrame, or find a similar module. 

from tsfresh import select_features, feature_selection
from tsfresh.feature_selection.relevance import calculate_relevance_table
relevance_table = calculate_relevance_table(features, def_param, ml_task='regression')


AttributeError: 'numpy.ndarray' object has no attribute 'sort_index'

In [53]:
#print(type(def_param))

<class 'pandas.core.frame.DataFrame'>
